- hosts: nfs
  become: yes
  roles:
    - nfs_server
  tasks:
    - name: Install NFS server
      yum:
        name: nfs-utils
        state: present

    - name: Start and enable NFS server
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Create shared directory
      file:
        path: /srv/nfs
        state: directory
        mode: '0755'

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/srv/nfs *(rw,sync,no_root_squash)"

    - name: Restart NFS service
      service:
        name: nfs-server
        state: restarted
